name: Build & Test

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
    branches:
      - master

  workflow_call:
    inputs:
      checkout-ref:
        type: string
        required: true
    secrets:
      github-token:
        required: true
      SOLUTIONS_TEAM_SLACK_WEBHOOK:
        required: true

jobs:
  build:
    name: Run Test Build All
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Commit
        if: github.event_name != 'workflow_call'
        uses: actions/checkout@v2

      - name: Checkout Using `checkout-ref`
        if: github.event_name == 'workflow_call'
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Run Build
        run: make test-build-all

      - name: Notify To Slack If Failed
        uses: lazy-actions/slatify@v3.0.0
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*[hex-monscape]* ${{ github.job }}"
          mention: "here"
          mention_if: "failure"
          channel: "#solutions-team-ci-cd"
          icon_emoji: ":haraaj:"
          username: "ci/cd-reporter"
          url: ${{ secrets.SOLUTIONS_TEAM_SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN || secrets.github-token }}
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Commit
        if: github.event_name != 'workflow_call'
        uses: actions/checkout@v2

      - name: Checkout Using `checkout-ref`
        if: github.event_name == 'workflow_call'
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Run Tests
        run: make test

      - name: Notify To Slack If Failed
        uses: lazy-actions/slatify@v3.0.0
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*[hex-monscape]* ${{ github.job }}"
          mention: "here"
          mention_if: "failure"
          channel: "#solutions-team-ci-cd"
          icon_emoji: ":haraaj:"
          username: "ci/cd-reporter"
          url: ${{ secrets.SOLUTIONS_TEAM_SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN || secrets.github-token }}
