name: ci

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  run-tests:
    name: Run Automated Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Current Commit
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ./.output/tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build docker-compose
        run: |
          docker buildx bake \
            -f ./deploy/local/tests/docker-compose.yml \
            --set *.cache-to="type=gha,mode=max" \
            --set *.cache-from="type=gha" --load  

      - name: Run Automated Tests
        run: make test

      - name: Test Build All Container Images
        run: make test-build-all

      - name: Notify To Slack If Failed
        uses: lazy-actions/slatify@v3.0.0
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*[hex-monscape]* ${{ github.job }}"
          mention: "here"
          mention_if: "failure"
          channel: "#solutions-team-ci-cd"
          icon_emoji: ":haraaj:"
          username: "ci/cd-reporter"
          url: ${{ secrets.SOLUTIONS_TEAM_SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
