name: Tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
    branches:
      - master
      - docs/refine-readme

jobs:
  # build:
  #   name: Test Build All Container Images
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Current Commit
  #       uses: actions/checkout@v3

  #     - name: Run Build All
  #       run: make test-build-all

  #     - name: Notify To Slack If Failed
  #       uses: lazy-actions/slatify@v3.0.0
  #       if: failure()
  #       with:
  #         type: ${{ job.status }}
  #         job_name: "*[hex-monscape]* ${{ github.job }}"
  #         mention: "here"
  #         mention_if: "failure"
  #         channel: "#solutions-team-ci-cd"
  #         icon_emoji: ":haraaj:"
  #         username: "ci/cd-reporter"
  #         url: ${{ secrets.SOLUTIONS_TEAM_SLACK_WEBHOOK }}
  #         commit: true
  #         token: ${{ secrets.GITHUB_TOKEN }}

  test-coverage:
    name: Run Tests & Code Coverage
    # needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Current Commit
        uses: actions/checkout@v3

      - name: Run Automated Tests
        run: make test

      - name: Install Go
        uses: actions/setup-go@v4.0.1

      - name: Install GOBadge
        run: go install github.com/AlexBeauchemin/gobadge@latest

      - name: Generate Coverage Badge
        run: |
          # generate coverage badge
          gobadge \
            -filename=./.output/cov-report/coverage.out \
            -green=80 \
            -target=README.md \
            -text=coverage \
            -link=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  
      - name: Auto Commit & Push Coverage Badge
        uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: "chore: apply code coverage badge"
          file_pattern: README.md

      - name: Notify To Slack If Failed
        uses: lazy-actions/slatify@v3.0.0
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*[hex-monscape]* ${{ github.job }}"
          mention: "here"
          mention_if: "failure"
          channel: "#solutions-team-ci-cd"
          icon_emoji: ":haraaj:"
          username: "ci/cd-reporter"
          url: ${{ secrets.SOLUTIONS_TEAM_SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
