name: ci

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build-all:
    name: Test Build All Container Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Commit
        uses: actions/checkout@v3

      - name: Run Build All
        run: make test-build-all

      - name: Notify To Slack If Failed
        uses: lazy-actions/slatify@v3.0.0
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*[hex-monscape]* ${{ github.job }}"
          mention: "here"
          mention_if: "failure"
          channel: "#solutions-team-ci-cd"
          icon_emoji: ":haraaj:"
          username: "ci/cd-reporter"
          url: ${{ secrets.SOLUTIONS_TEAM_SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}

  run-tests:
    name: Run Automated Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Current Commit
        uses: actions/checkout@v3

      - name: Run Automated Tests
        run: make test

      - name: Notify To Slack If Failed
        uses: lazy-actions/slatify@v3.0.0
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*[hex-monscape]* ${{ github.job }}"
          mention: "here"
          mention_if: "failure"
          channel: "#solutions-team-ci-cd"
          icon_emoji: ":haraaj:"
          username: "ci/cd-reporter"
          url: ${{ secrets.SOLUTIONS_TEAM_SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
