name: ci

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  run-tests:
    name: Run Automated Tests
    runs-on: self-hosted
    steps:
      - name: Checkout Current Commit
        uses: actions/checkout@v3

      - name: Run Test Build All
        run: make test-build-all

      - name: Run Automated Tests
        run: make test
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          
      - name: Send Coverage Report to Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: ./.output/cov-report/profile.cov

      - name: Notify To Slack If Failed
        uses: lazy-actions/slatify@v3.0.0
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*[hex-monscape]* ${{ github.job }}"
          mention: "here"
          mention_if: "failure"
          channel: "#solutions-team-ci-cd"
          icon_emoji: ":haraaj:"
          username: "ci/cd-reporter"
          url: ${{ secrets.SOLUTIONS_TEAM_SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
