name: ci

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  run-tests:
    name: Run Automated Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Current Commit
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ./.output/tmp/.buildx-cache
          key: ${{ runner.os }}-buildx

      - name: Build All Docker Images Necessary For Tests
        run: |
          docker buildx bake \
            -f ./deploy/local/tests/docker-bake.json \
            --set '*.cache-from'="type=local,src=./.output/tmp/.buildx-cache" \
            --set '*.cache-to'="type=local,dest=./.output/tmp/.buildx-cache" \
            --load 

      - name: Run Automated Tests
        run: make test

      - name: Notify To Slack If Failed
        uses: lazy-actions/slatify@v3.0.0
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*[hex-monscape]* ${{ github.job }}"
          mention: "here"
          mention_if: "failure"
          channel: "#solutions-team-ci-cd"
          icon_emoji: ":haraaj:"
          username: "ci/cd-reporter"
          url: ${{ secrets.SOLUTIONS_TEAM_SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
