name: coverage-badge

on:
  push:
    paths-ignore:
      - 'Makefile'
      - '**.md'
      - 'docs/**'
    branches: 
      - master
      - chore/use-coveralls

jobs:
  gen-badge:
    name: Update Coverage Badge
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Current Commit
        uses: actions/checkout@v3

      - name: Generate Coverage Report
        run: make test

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: ./.output/cov-report/profile.cov

      - name: Notify To Slack If Failed
        uses: lazy-actions/slatify@v3.0.0
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*[hex-monscape]* ${{ github.job }}"
          mention: "here"
          mention_if: "failure"
          channel: "#solutions-team-ci-cd"
          icon_emoji: ":haraaj:"
          username: "ci/cd-reporter"
          url: ${{ secrets.SOLUTIONS_TEAM_SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
