name: Test Services

on:
  push:
    branches-ignore:
      - master
      - feat/game-demo
  pull_request:
    paths-ignore:
      - 'Makefile'
      - '**.md'
      - 'docs/**'

  workflow_call:
    inputs:
      checkout-ref:
        type: string
        required: true
    secrets:
      github-token:
        required: true
      SOLUTIONS_TEAM_SLACK_WEBHOOK:
        required: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Commit
        if: github.event_name != 'workflow_call'
        uses: actions/checkout@v2

      - name: Checkout Using `checkout-ref`
        if: github.event_name == 'workflow_call'
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Run Tests
        run: make test

      - name: Notify To Slack If Failed
        uses: lazy-actions/slatify@v3.0.0
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*${{ github.job }}*"
          mention: "here"
          mention_if: "failure"
          channel: "#solutions-team-ci-cd"
          icon_emoji: ":haraaj:"
          username: "ci/cd-reporter"
          url: ${{ secrets.SOLUTIONS_TEAM_SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN || secrets.github-token }}
